# Generated by Django 5.2.1 on 2025-06-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=18, null=True, verbose_name="Телефон"
            ),
        ),
    ]
