# Generated by Django 5.2.1 on 2025-06-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agree_to_policy",
            field=models.BooleanField(
                default=False, verbose_name="Согласие с политикой конфиденциальности"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="policy_agreement_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата согласия с политикой"
            ),
        ),
    ]
