# Generated by Django 5.2.1 on 2025-06-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="carbohydrates",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="Углеводы, г",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="composition",
            field=models.TextField(blank=True, null=True, verbose_name="Состав"),
        ),
        migrations.AddField(
            model_name="product",
            name="energy",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Энергия, ккал"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="fats",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="Жиры, г",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="proteins",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="Белки, г",
            ),
        ),
    ]
