# Generated by Django 5.2.1 on 2025-06-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, max_length=18, verbose_name="Телефон"),
        ),
    ]
